#!/usr/bin/env bash

sms_="/opt/lampp/htdocs/sms/sms.php"
sms2="/opt/lampp/htdocs/sms/"


#CORES
red="\033[31m"
green="\033[32m"
bgreen="\033[32;1m"
pink="\033[35;1m"
cian="\033[36;1m"
fff="\033[m"
#========================================

function banner(){
cat <<EOF
 ____  __  __ ____    _   _    _    ____ _  _____ _   _  ____ 
/ ___||  \/  / ___|  | | | |  / \  / ___| |/ /_ _| \ | |/ ___|
\___ \| |\/| \___ \  | |_| | / _ \| |   | ' / | ||  \| | |  _ 
 ___) | |  | |___) | |  _  |/ ___ \ |___| . \ | || |\  | |_| |
|____/|_|  |_|____/  |_| |_/_/   \_\____|_|\_\___|_| \_|\____|
                                                              
EOF

}




#FUNÇÕES=========================================================================================

#ENVIANDO SMS
function sms(){
	read -p "Destinatario(DDD+Numero): " destino
	sed -i "s/dest0/$destino/" $sms_
	echo -e "${bgreen}Ok...${fff}" ; sleep 1s
	
	read -p "Mensagem: " mensagem
	sed -i "s/msg0/$mensagem/" $sms_
	echo -e "${pink}Enviando...${fff}" ; sleep 3s
	
	if curl 127.0.0.1/sms/sms.php;then
	echo -e "${bgreen}SMS ENVIADO COM SUCESSO PARA ${destino} ${fff}"
	sed -i "s/$mensagem/msg0/" $sms_
	sed -i "s/$destino/dest0/" $sms_
	else
	echo -e "${bred}Erro, operação não concluida!!!${fff}"
	fi
	echo ""
}

#MANIPULAÇÃO DOS ARQUIVOS DA API
function localfile(){
if [[ -d $sms2 ]];then
	rm -rf $sms2
	mkdir $sms2
	cp -r facilitamovelsms.php sms.php $sms2
else
	mkdir $sms2
	echo -e "${bgreen}Criando arquivos PHP em ${sms2} ...${fff}"
	cp -r facilitamovelsms.php sms.php $sms2
fi
}

#AJUDA
function helping(){
cat <<EOF
	-h		VER AJUDA.
	-c		ABRIR SITE DE CADASTRO FACILITAMOVEL.

	Caso não execute automaticamente, inicie o xampp manualmente.
	
	1) chmod 777 autosms.
	2) ./autosms.
	3) Adicionar conta facilitamovel e senha.
	4) Colocar destinatario ex: (17) 0000-0000.
	5) Run!!
	
	Versão: 2.0 - 2024
	Criado por: R4m0n3

	www.github.com/ram0ne
EOF
}

#CREDENCIAIS/DESTINO
function userpass(){

	read -p "Usuario: " _user
	read -s -p "Senha: " _pass
	echo " "
	echo -e "${bgreen}Salvando...${fff}"
	sleep 2s
	
	sed -i "s/user0/$_user/" $sms_
	sed -i "s/pass0/$_pass/" $sms_
}

#INCIANDO XAMPP
function xampp(){
if /opt/lampp/xampp status | grep -q "not"; then
 echo -e "${pink}INICIANDO XAMPP${fff}"
 /opt/lampp/xampp start
else
  echo -e "${bgreen}XAMP EM EXECUÇÃO...\nApache OK\nMySQL OK\nProFTPD OK\n${fff}"
fi
}

#INCIANDO======================================

if [[ $1 == "-h" ]];then
	helping
	banner
	exit 0
elif [[ $1 == "-c" ]];then
firefox "https://www.facilitamovel.com.br/loginsite.ft?utm_campaign=botao_conta&utm_source=pagina_inicial&utm_medium=pagina_inicial"
exit 0
fi

banner	#Banner
sleep 3s ; clear

echo -e "${pink}Lendo Arquivos PHP...${fff}"
localfile	#FUNÇÃO ARQUIVOS
sleep 1s
echo -e "${bgreen}OK...${fff}"

#===============================================

xampp #INICIANDO XAMPP
clear
banner
echo -e "${cian}Atualizado Por: Ramone, 11/2024, versão: 2.0"

echo -e "${pink}Faça login com sua conta FACILITAMOVEL...${fff}"
sleep 1s

userpass	#FUNÇÃO CONTA
sleep 1s
echo ""

while :; do
sms	#FUNÇÃO ENVIO
done

#==============================================
